sudo: required
services:
  - docker

before_install:
  - docker build -t mda1234/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mda1234/react-test npm test -- --coverage

after_success:
  - docker build -t mda1234/multi-client ./client
  - docker build -t mda1234/multi-nginx ./nginx
  - docker build -t mda1234/multi-server ./server
  - docker build -t mda1234/multi-worker ./worker
# log in to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
# take images and push to dockerhub
  - docker push mda1234/multi-client
  - docker push mda1234/multi-nginx
  - docker push mda1234/multi-server
  - docker push mda1234/multi-worker
